version: '3.5'

services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "8080:8080"
    volumes:
      - /run/udev:/run/udev:ro
      - ./config:/scrutiny/config
      - ./influxdb:/var/lib/influxdb2
    devices:
      - "/dev/sda"
      - "/dev/sdb"
